/** @format */

import RegisterModal from "./components/modals/RegisterModal";
import Navbar from "./components/navbar/Navbar";
import "./globals.css";
import { Nunito } from "next/font/google";
import ToasterProvider from "./providers/ToasterProvider";
import LoginModal from "./components/modals/LoginModal";
import getCurrentUser from "./actions/getCurrentuser";
import RentModal from "./components/modals/RentModal";
import ClientOnly from "./components/ClientOnly";
import SearchModal from "./components/modals/SearchModal";

const font = Nunito({ subsets: ["latin"] });

export const metadata = {
      title: "Airbnb",
      description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
      const currentUser = await getCurrentUser();
      console.log({currentUser})
      return (
            <html lang='en'>
                  <body className={font.className}>
                        <ClientOnly>
                              <SearchModal/>
                              <ToasterProvider /> {/* need to create toaster provider it will cause error if directly use Toaster*/}
                              <RegisterModal />
                              <LoginModal />
                              <RentModal />
                              <Navbar currentUser={currentUser} />
                        </ClientOnly>
                        <div className='pb-20 pt-28'>{children}</div>
                  </body>
            </html>
      );
}
